language: cpp
dist: trusty
sudo: required
branches:
  only:
    - master
    - support_ci
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-core libqt4-dev libqt4-gui qt4-dev-tools
  - sudo apt-get install libboost-all-dev
before_script:
  - cmake
script: ./qt_make.sh
