language: cpp
dist: trusty
sudo: false
matrix:
  include:
  - env: QT_VERSION=qt4
    os: linux
    compiler: gcc
    addons:
      apt:
        packages:
          - libqt4-core
          - libqt4-dev
          - libqt4-gui
          - qt4-dev-tools
  - env: QT_VERSION=qt4
    os: linux
    compiler: clang
    addons:
      apt:
        packages:
          - libqt4-core
          - libqt4-dev
          - libqt4-gui
          - qt4-dev-tools
  - env: QT_VERSION=qt5
    os: linux
    compiler: gcc
    addons:
      apt:
        packages:
          - qt5-default
          - qt5-qmake
          - qtbase5-dev-tools
  - env: QT_VERSION=qt5
    os: linux
    compiler: clang
    addons:
      apt:
        packages:
          - qt5-default
          - qt5-qmake
          - qtbase5-dev-tools
  - env: QT_VERSION=qt4
    os: osx
    osx_image: xcode9.2
    compiler: gcc
  - env: QT_VERSION=qt4
    os: osx
    osx_image: xcode8
    compiler: gcc
  - env: QT_VERSION=qt4
    os: osx
    osx_image: xcode9.2
    compiler: clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update -all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cartr/qt4/qt; fi
script: ./qt_make.sh
