language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
dist: trusty
addons:
  apt:
    packages:
      - libqt4-core
      - libqt4-dev
      - libqt4-gui
      - qt4-dev-tools
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update -all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cartr/qt4/qt; fi
script: ./qt_make.sh
