language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-core libqt4-dev libqt4-gui qt4-dev-tools
  - sudo apt-get install libboost-all-dev
  - add-apt-repository ppa:ubuntu-toolchain-r/test
  - apt-get update
  - apt-get install gcc-4.8 g++-4.8
  - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
before_script:
  - cmake
script: ./qt_make.sh
